### ISSUE TITLE
Unresolved import 'tokio::executor' with rustc 1.40

### ISSUE THREAD

**Issue by jburnett** [steffengy/tiberius#111]
The sample code fails to compile on Ubuntu 18.04 with rustc 1.40.  Steps:
Create a new project `cargo new rusql`
Copy _A simple example_ code from [tiberius docs](https://docs.rs/tiberius/0.3.2/tiberius/)
Add dependencies to the project's Cargo.toml
`tiberius = { version = "0.X", default-features=false,features=["chrono"] }`
`futures = "*"`
`futures-state-stream = "*"`
`tokio = "*"`
Build the project `cargo build`

Results:
`error[E0432]: unresolved import `tokio::executor`
 --> src/main.rs:7:12
  |
7 | use tokio::executor::current_thread;
  |            ^^^^^^^^ help: a similar path exists: 'tiberius::tokio::executor'

Tool versions:
`16:08 $ cargo --version`
`cargo 1.40.0 (bc8e4c8be 2019-11-22)`

`16:17 $ rustc --version`
`rustc 1.40.0 (73528e339 2019-12-16)`

OS:
`16:19 $ lsb_release -a`
`No LSB modules are available.`
`Distributor ID:	Ubuntu`
`Description:	Ubuntu 18.04.3 LTS`
`Release:	18.04`
`Codename:	bionic`

**Comment by jburnett** [comment]
Changing dependencies to 
`tiberius = { version = "0.3.*", default-features=false,features=["chrono"] }`
`futures = "0.3.*"`
`futures-state-stream = "0.2.*"`
`tokio = "0.1.*"`

made the error go away on my machine.

**Comment by steffengy** [comment]
You should use futures-state-stream="0.1".
Futures 0.3 might work with a  compatibility layer.

**Comment by jburnett** [comment]
The example now compiles when using 0.1 for futures & futures_state_stream.  Thanks!
